export const SECTIONS_ANIMATION_TIME = 0.75;
export const SUBMITTED_APPLICATIONS_ANIMATION_TIME = 0.5;
export const SLIDER_ANIMATION_TIME = 0.5;
export const SUBMIT_ANIMATION_TIME = 0.5;

export const AMOUNT_OF_SLIDER_PAGES = 4;